import type { NextPage } from 'next';
import { useContext } from 'react';
import { Header } from '../components/Header/Header';
import { AppContext } from '../contexts/appContext';
import { FullStatsWrapper } from '../components/AuthStatsWrapper/AuthStatsWrapper';
import { GeneralStatsWrapper } from '../components/GeneralStatsWrapper/GeneralStatsWrapper';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const {
    appState: { isAuthenticated },
  } = useContext(AppContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>CRSS Auth</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <div className={styles.mainContent}>
          <div>
            <h1>With auth system</h1>
            {isAuthenticated && (
              <div>
                <h2>General statistics</h2>
                <GeneralStatsWrapper />
                <br />
                <h2>Country statistics</h2>
                <FullStatsWrapper />
                <br />
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
