import type { NextPage } from 'next';
import { Header } from '../components/Header/Header';
import { SingleStatsWrapper } from '../components/SingleStatsWrapper/SingleStatsWrapper';

import Head from 'next/head';
import styles from '../styles/Home.module.css';

const NoAuth: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CRSS-No-auth</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />

        <div>
          <SingleStatsWrapper />
        </div>
      </main>
    </div>
  );
};

export default NoAuth;
