import type { NextPage } from 'next';
import { Header } from '../components/Header/Header';
import { SingleStatsWrapper } from '../components/NoAuthStatsWrapper/NoAuthStatsWrapper';
import Head from 'next/head';
import styles from '../styles/Home.module.css';


const NoAuth: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CRSS NoAuth</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <div className={styles.mainContent}>
          <div>
            <h1>Without auth system</h1>
            <SingleStatsWrapper />
          </div>
        </div>
      </main>
    </div>
  );
};

export default NoAuth;
